id: A789C7CCF
base_file: f1260.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:23:21.485459
  last_modified_at: 2022-06-17 12:23:21.485469
